version: '3'

services:
  osekai_database:
    image: mysql:5.7.42
    environment:
      - MYSQL_ROOT_PASSWORD=admin # Change it to a more secure one if needed
      - MYSQL_DATABASE=osekai
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - ./db-data/:/var/lib/mysql
  osekai_website:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    environment:
      - ROOT_URL=localhost:8080
      - OSU_API_V1_KEY= # Required
      - OSU_OAUTH_CLIENT_SECRET= # Required
      - OSU_OAUTH_CLIENT_ID= # Required
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=osekai
      - DB_HOSTNAME=osekai_database
    volumes:
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./:/var/www/html:rw
    ports:
      - 8080:80
  osekai_adminer:
    image: adminer
    ports:
      - 3000:8080
