version: '3'

services:
  database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=admin # Change it to a more secure one if needed
      - MARIADB_DATABASE=osekai
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
  website:
<<<<<<< HEAD
    extra_hosts:
      - "host.docker.internal:host-gateway"
=======
>>>>>>> d0e8b05 (Add Docker support)
    build: .
    environment:
      - ROOT_URL=localhost:8080
      - OSU_API_V1_KEY= # Required
      - OSU_OAUTH_CLIENT_SECRET= # Required
      - OSU_OAUTH_CLIENT_ID= # Required
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=osekai
      - DB_HOSTNAME=database
<<<<<<< HEAD
    volumes:
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./:/var/www/html:rw
=======
>>>>>>> d0e8b05 (Add Docker support)
    ports:
      - 8080:80
  adminer:
    image: adminer
    ports:
      - 3000:8080
